version: '3.9'

services:

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile-prod
        ports:
            - "3000:80"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - frontend

    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            - MONGO_INITDB_ROOT_USERNAME=fullstack
            - MONGO_INITDB_ROOT_PASSWORD=vivanaturals
            - MONGO_INITDB_DATABASE=fullstackdemo
            - MONGODB_DATA_DIR=/data/db
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn --bind 0.0.0.0:5000 app:app
        expose:
            - 5000
        environment:
            - MONGODB_HOST=mongodb
            - MONGODB_USERNAME=fullstack
            - MONGODB_PASSWORD=vivanaturals
        volumes:
            - appdata:/app
        depends_on: 
            - mongodb
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local